import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import QueryProvider from "./providers/query-provider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.className}`}>
      <body>
        <QueryProvider>
          <Toaster richColors position="top-center" closeButton />
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
